### ISSUE TITLE
Exception when using CatchWinFormsExceptions with Coderr 2.*

### ISSUE THREAD

**Issue by SamKr** [coderrapp/codeRR.Client.WinForms#1]
Since I've installed the Coderr.Client v2.* package, I keep getting the following exception when CatchWinFormsExceptions is enabled:

`System.MissingMethodException: Method not found: 'Coderr.Client.ContextProviders.ContextProvidersRegistrar Coderr.Client.Config.CoderrConfiguration.get_ContextProviders()'.
   at Coderr.Client.WinForms.ConfigExtensions.CatchWinFormsExceptions(CoderrConfiguration configurator)`

**Comment by jgauffin** [comment]
I bumped the core package to v2.0 since it contained breaking changes.

I've however created a v2.0 of the WinForms library too now.
